on:
    workflow_call:
        inputs:
            drupal-core:
                required: true
                type: string
            php-version:
                required: true
                type: string

        steps:
            -   name: Build module including dependencies dependencies
                run: |
                    cd modules/test_support
                    composer --no-interaction --no-progress --prefer-dist --optimize-autoloader install

            -   name: Setup PHP, with composer and extensions
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ input.php-version }}
                    coverage: none

            -   name: Get composer cache directory
                id: composercache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache composer dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composercache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-

            -   name: Install Drupal core dependencies
                run: composer --no-interaction --no-progress --prefer-dist --optimize-autoloader install

            -   name: Run PHPUnit tests
                run: |
                    modules/test_support/vendor/bin/paratest \
                    --path modules/test_support/tests \
                    -c modules/test_support/phpunit.xml \
                    --bootstrap core/tests/bootstrap.php  \
                    --testsuite unit,kernel
