name: CI
on: [ push ]
jobs:
    drupal-10-matrix:
        name: Drupal ${{ matrix.drupal-core }} - PHP ${{ matrix.php-versions }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                drupal-core: [ '10.0.x' ]
                php-versions: [ '8.1', '8.0' ]
        steps:
            -   name: Build and test
                uses: ./.github/workflows/build-and-test.yml
                with:
                    drupal-core: ${{ matrix.drupal-core }}
                    php-version: ${{ matrix.php-versions }}
