name: Lint
on: [ push ]
jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: "Lint (Syntax)"
        run: composer lint

      - uses: actions/checkout@v1
      - name: "Lint (Code Style)"
        uses: aglipanci/laravel-pint-action@2.0.0
        with:
          verboseMode: true
          testMode: true
          pintVersion: 1.8.0

      - name: "Lint (Static Analysis)"
        run: composer stan
