name: Test
on: [push]
env:
  MODULE_NAME: "test_support"
jobs:
    drupal-10-matrix:
        name: Drupal ${{ matrix.drupal-core }} - PHP ${{ matrix.php-versions }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                drupal-core: ['10.0.x']
                php-versions: ['8.1']
        steps:
            - name: Checkout Drupal core
              uses: actions/checkout@v2
              with:
                  repository: drupal/drupal
                  ref: ${{ matrix.drupal-core }}

            # The next two steps exposes $DRUPAL_ROOT and $MODULE_FOLDER environment
            # variables.
            #
            # They have to be set in separate steps because $DRUPAL_ROOT variable
            # won't be accessible in currently active step.
            # You can access them either with $DRUPAL_ROOT and $MODULE_FOLDER or
            # ${{ env.DRUPAL_ROOT }} and ${{ env.MODULE_FOLDER }}.
            - name: Define DRUPAL_ROOT env variable
              run: echo "DRUPAL_ROOT=$HOME/drupal" >> $GITHUB_ENV

            # Change the module folder according to your needs, it's probably either
            # modules/contrib/$MODULE_NAME or modules/custom/$MODULE_NAME.
            - name: Set module folder
              run: |
                echo "MODULE_FOLDER=$DRUPAL_ROOT/modules/$MODULE_NAME" \
                  >> $GITHUB_ENV

            - name: Checkout module
              uses: actions/checkout@v2
              with:
                  path: modules/test_support

            - name: Install module dependencies
              run: |
                cd modules/test_support
                composer --no-interaction --no-progress --prefer-dist --optimize-autoloader install

            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  coverage: none

            - name: Get composer cache directory
              id: composercache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache composer dependencies
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composercache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install Drupal core dependencies
              run: composer --no-interaction --no-progress --prefer-dist --optimize-autoloader install

            - name: Debug PHPUnit
              run: ls modules/test_support/vendor

            - name: Run PHPUnit tests
              working-directory: ${{ env.DRUPAL_ROOT }}
              run: |
                vendor/bin/phpunit --bootstrap $DRUPAL_ROOT/core/tests/bootstrap.php \
                -c $MODULE_FOLDER/phpunit.xml $MODULE_FOLDER
